const GET_TREE = 'GET_TREE';
const NODE_CREATE = 'NODE_CREATE';
const NODE_RENAME = 'NODE_RENAME';
const NODE_DELETE = 'NODE_DELETE';

const RENDER_TREE = 'RENDER_TREE';
const ERROR = 'ERROR';
const TOGGLE = 'TOGGLE';

export { 
  GET_TREE,
  NODE_CREATE,
  NODE_RENAME,
  NODE_DELETE,
  RENDER_TREE,
  ERROR,
  TOGGLE
};
